version: '3.1'
services:
  sonarr:
    image: 'lscr.io/linuxserver/sonarr:latest'
    container_name: sonarr
    environment:
      - PUID=13001
      - PGID=13000
      - UMASK=002
      - TZ="America/Montevideo"
    volumes:
      - '/mnt/d/Descargas/Media-Servers/config/sonarr-config:/config'
      - '/mnt/d/Descargas/Media-Servers/data:/data'
    ports:
      - '8989:8989'
    restart: unless-stopped
  radarr:
    image: 'lscr.io/linuxserver/radarr:latest'
    container_name: radarr
    environment:
      - PUID=13002
      - PGID=13000
      - UMASK=002
      - TZ="America/Montevideo"
    volumes:
      - '//mnt/d/Descargas/Media-Servers/config/radarr-config:/config'
      - '/mnt/d/Descargas/Media-Servers/data:/data'
    ports:
      - '7878:7878'
    restart: unless-stopped
  prowlarr:
    image: 'lscr.io/linuxserver/prowlarr:develop'
    container_name: prowlarr
    environment:
      - PUID=13006
      - PGID=13000
      - UMASK=002
      - TZ="America/Montevideo"
    volumes:
      - '/mnt/d/Descargas/Media-Servers/config/prowlarr-config:/config'
    ports:
      - '9696:9696'
    restart: unless-stopped
  plex:
    image: 'lscr.io/linuxserver/plex:latest'
    container_name: plex
    network_mode: host
    environment:
      - 'PUID=${UID}'
      - PGID=13000
      - VERSION=docker
      - PLEX_CLAIM=claim-yy15WX32hvdqXjFzXBPg
    volumes:
      - '/mnt/d/Descargas/Media-Servers/config/plex-config:/config'
      - '/mnt/d/Descargas/Media-Servers/data/media:/media'
    restart: unless-stopped
  jellyfin:
    image: ghcr.io/confusedpolarbear/jellyfin-intro-skipper
    container_name: jellyfin
    user: 1000:1000
    environment:
      - 'PUID=${UID}'
      - PGID=13000
      - UMASK=002
      - TZ="America/Montevideo"
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]
    volumes:
      # - /dev/nvidia-caps:/dev/nvidia-caps
      # - /dev/nvidia0:/dev/nvidia0
      # - /dev/nvidiactl:/dev/nvidiactl
      # - /dev/nvidia-modeset:/dev/nvidia-modeset
      # - /dev/nvidia-uvm:/dev/nvidia-uvm
      # - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - '/mnt/d/Descargas/Media-Servers/config/jellyfin-config:/config'
      - '/mnt/d/Descargas/Media-Servers/data/media:/data'
    ports:
      - '8096:8096'
    restart: unless-stopped
  qbittorrent:
    image: 'lscr.io/linuxserver/qbittorrent:latest'
    container_name: qbittorrent
    environment:
      - PUID=13007
      - PGID=13000
      - UMASK=002
      - TZ="America/Montevideo"
      - WEBUI_PORT=8081
    volumes:
      - '/mnt/d/Descargas/Media-Servers/config/qbittorrent-config:/config'
      - '/mnt/d/Descargas/Media-Servers/data/torrents:/data/torrents'
    ports:
      - '8081:8081'
      - '6881:6881'
      - '6881:6881/udp'
    restart: unless-stopped
  # kodi:
  #   container_name: kodi
  #   image: linuxserver/kodi-headless
  #   restart: always
  #   environment:
  #     - PGID=1000
  #     - PUID=1000
  #     - TZ=America/Chicago
  #   volumes:
  #     - /home/isma/Descargas/Media-Servers/config/kodi:/config/.kodi
  #   ports:
  #     - 8082:8080
  #     - 9090:9090
  #     - "9777:9777/udp"
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - '/home/isma/Descargas/Media-Servers/config/bazarr:/config'
      - '/mnt/d/Descargas/Media-Servers/data/media:/data'
    restart: unless-stopped
