version: "3.8"
services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Montevideo
    volumes:
      - /mnt/c/media-servers/config/sonarr-config:/config
      - /mnt/d/media-servers/data:/data
      - /mnt/c/media-servers/data:/mnt
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Montevideo
    volumes:
      - /mnt/c/media-servers/config/radarr-config:/config
      - /mnt/c/media-servers/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
  lidarr:
    container_name: lidarr
    image: ghcr.io/hotio/lidarr
    ports:
      - 8686:8686
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /mnt/c/media-servers/config/lidarr:/config
      - /mnt/d/media-servers/data:/data
      - /mnt/c/media-servers/data:/mnt
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    ports:
      - 6969:6969
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Montevideo
    volumes:
      - /mnt/c/media-servers/data:/data
      - /mnt/c/media-servers/config/whisparr-config:/config
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Montevideo
    volumes:
      - /mnt/c/media-servers/config/prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-yy15WX32hvdqXjFzXBPg
    volumes:
      - /mnt/c/media-servers/config/plex-config:/config
      - /mnt/c/media-servers/data/media:/media
      - /mnt/d/media-servers/data/media:/mnt
    restart: unless-stopped
  jellyfin:
    image: ghcr.io/confusedpolarbear/jellyfin-intro-skipper
    container_name: jellyfin
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montevideo
    volumes:
      - /mnt/c/media-servers/config/jellyfin-config:/config
      - /mnt/c/media-servers/data/media:/data
      - /mnt/d/media-servers/data/media:/mnt
    restart: unless-stopped
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
    volumes:
      - /mnt/c/media-servers/config/navidrome:/data
      - /mnt/d/media-servers/data/media/music:/music:ro
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent # should be owner of volumes
    ports:
      - 8081:8081
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8081/tcp,8081/udp
    volumes:
      # Optional: put your config options customization here. Examples:
      - /mnt/c/media-servers/config/qbittorrent-config:/config
      - /mnt/c/media-servers/data/torrents:/data/torrents
    restart: unless-stopped
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Montevideo
    volumes:
      - /mnt/c/media-servers/config/bazarr:/config
      - /mnt/c/media-servers/data/media:/data
      - /mnt/d/media-servers/data/media:/mnt
    restart: unless-stopped
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/c/media-servers/config/homarr:/app/data/configs
      - /mnt/c/media-servers/config/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/c/media-servers/config/homarr/data:/data
    ports:
      - 7575:7575
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /mnt/c/media-servers/config/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montevideo
    ports:
      - 8181:8181
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tokyo
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - /mnt/c/media-servers/config/overseerr:/app/config
    restart: unless-stopped
  stash:
    container_name: stash
    image: ghcr.io/hotio/stash
    ports:
      - 9999:9999
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /mnt/c/media-servers/config/stash:/config
      - /mnt/c/media-servers/data/media:/data
    restart: unless-stopped
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /mnt/c/media-servers/config/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
networks: {}
