version: "3.8"
services:
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /mnt/c/media-servers/config/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montevideo
    ports:
      - 8181:8181
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tokyo
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - /mnt/c/media-servers/config/overseerr:/app/config
    restart: unless-stopped
  stash:
    container_name: stash
    image: ghcr.io/hotio/stash
    ports:
      - 9999:9999
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /mnt/c/media-servers/config/stash:/config
      - /mnt/c/media-servers/data/media:/data
    restart: unless-stopped
networks: {}
